#!/bin/sh
#
# Kontrol-repo-setup
#
# Setup repository configuration and pkg ABI for Kontrol/pfSense systems.

usage() {
	me=$(basename $0)
	cat << EOD >&2
Usage: ${me} [-U]
	-U          - Do not update repository information
EOD
}

repo_is_custom() {
	local _pkg_repo_conf_path="${1}"

	if [ -n "$(echo ${_pkg_repo_conf_path} | grep ${product}-repo-custom)" ]; then
		return 0
	fi
	return 1
}

validate_repo_conf() {
	local _repo_conf="/usr/local/etc/pkg/repos/${product}.conf"
	local _default="/usr/local/share/${product}/pkg/repos/${product}-repo.conf"

	pkg_repo_conf_path=$(read_xml_tag.sh string system/pkg_repo_conf_path)
	if [ -z "${pkg_repo_conf_path}" -o ! -f "${pkg_repo_conf_path}" ]; then
		pkg_repo_conf_path="${_default}"
	fi

	mkdir -p /usr/local/etc/pkg/repos

	if [ -e "${_repo_conf}" -a ! -L "${_repo_conf}" ]; then
		rm -f ${_repo_conf}
	fi

	if [ "$(readlink ${_repo_conf} 2>/dev/null)" != \
	    "${pkg_repo_conf_path}" ]; then
		ln -sf ${pkg_repo_conf_path} ${_repo_conf}
	fi
}

abi_setup() {
	local _freebsd_version=$(uname -r)
	local _osversion=$(sysctl -n kern.osreldate 2>/dev/null)
	local _pkg_repo_conf="/usr/local/etc/pkg/repos/${product}.conf"

	CUR_ABI="FreeBSD:${_freebsd_version%%.*}:${arch}"
	CUR_OSVERSION="${_osversion}"

	if [ ! -e ${_pkg_repo_conf} ]; then
		validate_repo_conf
	fi

	local _repo_abi_file=$(readlink ${_pkg_repo_conf})

	if [ -f ${_repo_abi_file%%.conf}.abi ]; then
		ABI=$(cat ${_repo_abi_file%%.conf}.abi)
	else
		ABI=${CUR_ABI}
	fi

	if [ -f ${_repo_abi_file%%.conf}.osversion ]; then
		OSVERSION=$(cat ${_repo_abi_file%%.conf}.osversion)
	else
		OSVERSION=${CUR_OSVERSION}
	fi

	echo "ABI=${ABI}" > /usr/local/etc/pkg.conf
	echo "OSVERSION=${OSVERSION}" >> /usr/local/etc/pkg.conf

	AUTH_CA="/etc/ssl/netgate-ca.pem"
	AUTH_CERT="/etc/ssl/pfSense-repo-custom.cert"
	AUTH_KEY="/etc/ssl/pfSense-repo-custom.key"
	if repo_is_custom "${pkg_repo_conf_path}" -a -f "${AUTH_CA}" \
	    -a -f "${AUTH_CERT}" -a -f "${AUTH_KEY}" ; then
		cat << EOF >> /usr/local/etc/pkg.conf
PKG_ENV {
	SSL_CA_CERT_FILE=${AUTH_CA}
	SSL_CLIENT_CERT_FILE=${AUTH_CERT}
	SSL_CLIENT_KEY_FILE=${AUTH_KEY}
}
EOF
	fi

	if [ "${arch}" = "aarch64" ]; then
		cat << EOF >> /usr/local/etc/pkg.conf
PKG_ENV {
	OPENSSL_CONF=/etc/thoth/openssl.cnf
	SSL_CA_CERT_FILE=/etc/thoth/ca.pem
	SSL_CLIENT_CERT_FILE=/etc/thoth/device.pem
	SSL_CLIENT_KEY_FILE=/etc/thoth/key.pem
}
EOF
	fi
}

dont_update=""
while getopts "U" opt; do
	case ${opt} in
		U)
			dont_update=1
			;;
		*)
			usage
			exit 1
			;;
	esac
done

arch=$(uname -p)
product=$(php -n /usr/local/sbin/read_global_var product_name Kontrol)

validate_repo_conf
abi_setup

repo_state_file="/var/run/${product}_repo_conf_path"
repo_conf_path="/usr/local/etc/pkg/repos/${product}.conf"
current_repo_conf="$(readlink ${repo_conf_path} 2>/dev/null)"
if [ -z "${current_repo_conf}" -a -f "${repo_conf_path}" ]; then
	current_repo_conf="${repo_conf_path}"
fi
if [ -n "${current_repo_conf}" ]; then
	if [ -f "${repo_state_file}" ]; then
		previous_repo_conf="$(cat "${repo_state_file}")"
		if [ "${previous_repo_conf}" != "${current_repo_conf}" ]; then
			rm -f "/var/run/${product}_version" \
			    "/var/run/${product}_version.rc"
		fi
	fi
	echo "${current_repo_conf}" > "${repo_state_file}"
fi

if [ -z "${dont_update}" ]; then
	/usr/local/bin/php -r 'require_once("pkg-utils.inc");update_repos();'
	/usr/local/sbin/pkg-static update -f >/dev/null 2>&1
fi

exit 0
